# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build:
    cmds:
      - go build -o output/ .
    sources:
      - '**/*.go'
    generates:
      - output/hass-telegram-bot
    method: checksum
    silent: false

  lint:
    cmds:
      - golangci-lint run
    silent: false
